version: "2"

networks:
  projectTemplate:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    container_name: nginx-proxy-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./tmp:/tmp
    networks:
      - projectTemplate

  express:
    build: 
      context: .
      dockerfile: express.Dockerfile
    container_name: express-dashboard
    restart: always
    networks:
      - projectTemplate
    volumes:
      - ./app:/usr/src/app
    
  library:
    image: httpd:latest
    container_name: httpd-static-templates
    restart: always
    volumes:
      - ./library:/usr/local/apache2/htdocs/library/
    networks:
      - projectTemplate