version: "3"

networks: 
  projectTemplate:
    driver: bridge

services:
  # nginx web proxy
  nginx:
    build:
      context: .
      dockerfile: express.Dockerfile
    ports:
      - "8080:8080" # expose 80 on host and sent to 80 in container
    container_name: express
    networks:
      - projectTemplate
    restart: always
    volumes:
      - ./app:/usr/src/app
      - ./html:/usr/src/static
      - ./assets:/usr/src/assets
